joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

opcua_controller:
  ros__parameters:
    type: gpio_controllers/GpioCommandController
    gpios:
      - robot_command
      - robot_sensor

    command_interfaces:
      robot_command:
        - interfaces:
          - commandPos_0
          - commandPos_1
          - my_integer_interface

    state_interfaces:
      robot_sensor:
        - interfaces:
          - commandPos_0
          - commandPos_1
          - currentPos_0
          - currentPos_1
          - my_integer_interface
